### ISSUE TITLE
encrypt sensitive data in chopper Header Interceptor

### ISSUE THREAD

**Issue by jesseframework** [lejard-h/chopper#146]
Hello team,
Is it possible to encrypt sensitive data in chopper header Interceptor using some kind of annotation on password or another other data you want to exclude form the log.

**Comment by stewemetal** [comment]
Hi!

It's definitely possible to encrypt request headers using Interceptors, which have access to the Request object of each network call. You can modify the Request any way you want in an Interceptor.

However, providing any concrete means of encryption, with annotations or otherwise, doesn't seem to be the responsibility of a networking library to implement.

You can use something like [encrypt](https://pub.dev/packages/encrypt) to do the encryption on your client side (Flutter app) in Interceptor(s).

**Comment by stewemetal** [comment]
I'm closing this issue as the solution is a method achievable with the current state of Chopper.

@jesseframework please feel free to reopen this issue any time.
