### ISSUE TITLE
how to update interceptors realtime ?

### ISSUE THREAD

**Issue by akshaybhange** [lejard-h/chopper#188]
I'm using the below-given code for a network request. after the first API call, I receive a session key which is stored in preferences. but in the second API call interceptor is not adding values for preferences. If I restart the app then only it works. 

Any way to get real-time updates of interceptors?

```
class ApiClients {
  final PrefManager prefManager;

  ApiClients(this.prefManager);

  ChopperClient getHraApiClient() {
    return ChopperClient(
        baseUrl: ApiConst.baseUrlHra,
        converter: JsonConverter(),
        errorConverter: JsonConverter(),
        services: [MyApiService.create()],
        interceptors: getInterceptors());
  }

  List<dynamic> getInterceptors() {
    List<dynamic> interceptors = List<dynamic>();

    final String sessionKey = prefManager.hra.sessionKey;
    final String userEmailId = prefManager.user.emailId;

    interceptors.add(HeadersInterceptor({
      ApiConst.headerSessionKey: sessionKey ?? '',
      ApiConst.headerUserEmailId: userEmailId ?? '',
    }));

    interceptors.add(HttpLoggingInterceptor());
    return interceptors;
  }
}
```

**Comment by stewemetal** [comment]
In `getInterceptors()`, you're creating a `HeadersInterceptor` with hardcoded values. Those values are read from `prefManager` *once* when you create your `ChopperClient`. Of course, prefs will be empty on the first app start, so you're essentially hardcoding `null`s. After an app restart, the prefs are read again, and because you received and saved a session key previously, this time you're hardcoding that session key.

A solution would be a custom Interceptor which reads the session key dynamically on every network call:

```dart
class ApiKeyInterceptor implements RequestInterceptor {
  final PrefManager prefManager;

  ApiKeyInterceptor(this.prefManager);

  @override
  FutureOr<Request> onRequest(Request request) {
    return request.copyWith(
        parameters: Map.from(request.parameters)
          ..[ApiConst.headerSessionKey] = prefManager.hra.sessionKey
          ..[ApiConst.headerUserEmailId] = prefManager.user.emailId
    );
  }
}
```

Then your `getInterceptors()` could look like this:

```dart
List<dynamic> getInterceptors() {
  List<RequestInterceptor> interceptors = List();

  interceptors.add(SessionKeyInterceptor(prefManager));
  interceptors.add(HttpLoggingInterceptor());
  return interceptors;
}
```
