### ISSUE TITLE
Chopper client would not be an @immutable instance.

### ISSUE THREAD

**Issue by kiruto** [lejard-h/chopper#19]
Hi lejard-h,

When ChopperClient#dispose called, it means all resources and references will be released.
I think it will be better if the references of service instances and httpClient can be released on dispose.
Or the client instance and service instances will be pairs of circular reference, and will never be released from memory.
So the solution may make some parts of the member field mutable, and set null on dispose.

**Comment by lejard-h** [comment]
Hello kiruto

on the dev channel https://github.com/lejard-h/chopper/blob/dev/chopper/lib/src/base.dart

the dispose function is implemented like this.
```
/// dispose [ChopperClient] to clean memory
  void close() {
    _requestController.close();
    _responseController.close();
    _responseErrorController.close();
    if (_clientIsInternal) {
      httpClient.close();
    }
  }
```

I don't need to dispose services since they don't handle resources but I need to close the http client connection in the case I created internally ( I don't want to close something that I don't own).

However I could call `clear` function on following resources to be sure I don't keep reference on anything if you prefere

```
final Map<Type, ChopperService> _services = {};
final _requestInterceptors = [];
final _responseInterceptors = [];
```

**Comment by lejard-h** [comment]
Can you explain what you mean by "they are a pair of circular reference" I am not sure to understand

**Comment by kiruto** [comment]
Sorry for my poor English.
Like the chart below.
![untitled diagram](https://user-images.githubusercontent.com/2758180/51671212-c0a0bf00-200b-11e9-9541-3901df5699ef.png)

When client disconnected from GC root, it is still reachable because service instances owns it, and cause httpClient cannot be released.

When a service instance is  disconnected from GC root, it also cannot be released.

If there is numbers of clients / services and not be released, I'm worry about it may cause memory leak.

**Comment by lejard-h** [comment]
`2.0.0` released
