### ISSUE TITLE
Upgrade to use `analyzer ^5.0.0`

### ISSUE THREAD

**Issue by RoarGronmo** [lejard-h/chopper#377]
Trying to upgrade dependencies and find that resolving is lacking behind due to `chopper` using not latest dependency of `analyzer`. Chopper libraries seems to use `analyzer 4.4.0`. Other dependecies are using `analyzer ^5.0.0`.

```
Because no versions of drift_dev match >=2.2.0 <2.2.0+1 and drift_dev >=2.2.0+1 depends on analyzer ^5.0.0, drift_dev >=2.2.0 requires analyzer ^5.0.0.
And because chopper_generator >=5.0.1 depends on analyzer ^4.4.0, drift_dev >=2.2.0 is incompatible with chopper_generator >=5.0.1.
So, because mwork depends on both chopper_generator ^5.1.0 and drift_dev ^2.2.0, version solving failed.
pub finished with exit code 1
```

Please upgrade `chopper` libraries to use `analyzer ^5.0.0`

**Comment by techouse** [comment]
I think that bumping it up to `^5.0.0` is a bit harsh [because that version removed quite a few deprecated APIs](https://pub.dev/packages/analyzer/changelog#500). It would probably also warrant a minor Chopper version release rather than just a patch release, so I went with `>=4.4.0 <6.0.0` which should give users a gentler transition.
