### ISSUE TITLE
_TypeError thrown on unsuccessful response

### ISSUE THREAD

**Issue by ptrbrynt** [lejard-h/chopper#71]
I'm using Chopper 2.5.0 and a custom converter which works with `built_value`. If the API returns an error, Chopper returns a `Response<dynamic>` rather than a response of the expected type. This is causing a `_TypeError`.

**Comment by Kavantix** [comment]
@lejard-h I also ran into this, this happens because of the removal of the throw statement when the response is not successful.
Is there a particular reason you removed the throw?

**Comment by lejard-h** [comment]
Sorry, that case was not correctly tested. 
Related to https://github.com/lejard-h/chopper/issues/68

I am working on a patch now, it will land soon but with some change in the api.
Basically this is how you handle error now

```dart
if (response.isSuccessful) {
  final body = response.body;
} else {
  final error = response.error;
}
```

**Comment by Kavantix** [comment]
Would it be possible to release a version without this api change as 2.5.1. And release the change as 3.0.0.
Because when people specify the package in their pubspec using ^2.4.2 they will get 2.5.0 since this syntax means anything between 2.0.0 and 3.0.0.

For fixing the type error, it might be nice to make a response have two types, a body type and an error type.

**Comment by lejard-h** [comment]
yes just published `2.5.2` without the change and `3.0.0` with the change.

About specifying the error type on the response. I am not sure it is a good idea errors are dynamic by nature, even if your converter is constantly generating the same type, at some point you will need to check what kind of error you are manipulating.

```dart
MyError error = response.error;
if (error.type == MyError.something) {
  ...
} else {
  ...
}

// not so different from
Object error = response.error;
if (error is MyErrorSomething) {
  ...
} else {
  ...
}
```

It is also a big breaking change since all `Response<Body>` won't be valid anymore and it will force you to specify the type of your error `Response<Body, Error>` all the time, for now I want to keep service definition simple, I am not sure I want to introduce something like that for now maybe later.

**Comment by Kavantix** [comment]
@lejard-h the 2.5.2 release doesn't seem to have the throw statement in it.

**Comment by ptrbrynt** [comment]
@lejard-h Would it be possible to add an `errorBody` property to a `Response` and make that `dynamic`? Then in the case of an error the `body` could be `null`.

**Comment by lejard-h** [comment]
Should be good with last version `3.0.0`
https://pub.dev/documentation/chopper/latest/chopper/Response/error.html
